### ISSUE TITLE
Autoload issue after installation and use

### ISSUE THREAD

**Issue by plasid** [nette/php-generator#122]
$ composer require nette/php-generator --dev 
THEN LATER IN MY OWN CODE 
use Nette\PhpGenerator\ClassType;
.
$class = new ClassType('Demo');
.
.
THEN 
Error: Nette\PhpGenerator\ClassType not found...
BUT 
When you: composer require without the --dev flag then all works fine.
Is there a way to install it as a dev dependency and get it to autoload/resolve correctly?

**Comment by mabar** [comment]
It should work identically with and without --dev flag. Only difference is dev dependencies are not installed if you run `composer install --no-dev` instead of `composer install`

If it does not work with `composer install` - do you have any Composer plugins installed, that could modify autoloading or installation directory?

**Comment by mabar** [comment]
It just happened to me too. Seems like it is a Composer bug during plugins installation phase. Class which plugin uses is not available because it is from dependency that is being updated.

Full reinstall does not trigger the issue, only update from 3.x version to 4.x

![image](https://user-images.githubusercontent.com/20974277/209130483-093ee13a-c201-4440-b5e5-187be2da96e1.png)

**Comment by WalterWoshid** [comment]
Had the same issue, try deleting the `vendor` folder and the `composer.lock` file and run `composer update`

**Comment by dg** [comment]
Will you try reporting it to composer?
